project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd 
        text: Home 
      - href: about.qmd
        text: About
      - text: CV
        href: cv.qmd
  
      - text: Computation
        menu:
          - text: "Fourier Analysis"
            href: computation/FourierAnalysis.html
          - text: "Discrete Fourier Transform"
            href: computation/DiscreteFourierTransform_DFT.html

          - text: "Mandelbrot and Chaos"
            href: computation/MandelbrotAndChaos.html
      - text: Physics
      - text: Philosophy
  page-footer:
    center: "Thank you for visiting."
  cookie-consent: true

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto


