project:
  type: website
  output-dir: docs

website:
  title: "Anoj Khadka"
  navbar:
    title: ""
    left:
      - href: index.qmd
        text: Home
      - Computation
      - About
      - CV
  favicon: ""
  page-footer:
    center: "Thank you for visiting."
  cookie-consent: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto


